name: Release

on:
  push:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Create mock config
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "src/config.ts"
          FILE_BASE64: "Y29uc3QgY29uZmlnID0gewogIGdvbGRUaHJlc2hvbGRzOiB7CiAgICBhcm1vaXJlOiA1MDAsCiAgfSwKICBtYW5hVGhyZXNob2xkczogewogICAgZWFydGhxdWFrZTogMTUwLAogIH0sCiAgaGVhZGVyczogewogICAgJ3gtYXBpLXVzZXInOiAndXNlcicsCiAgICAneC1hcGkta2V5JzogJ2tleScsCiAgfSwKfQoKZXhwb3J0IGRlZmF1bHQgY29uZmlnCg=="

      - name: Run tests and linting
        run: |
          npm install
          npm test
        env:
          CI: true

      - name: Create release using semantic-release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17.1.1
          extra_plugins: |
            @semantic-release/changelog@5.0.1
            @semantic-release/git@9.0
        env:
          # GITHUB_TOKEN is added automatically by GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

